services:

  motivatr-payment-app:
    container_name: motivatr-payment-app
    image: motivatr-payment-app-image:latest
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    env_file:
      - .env.app
      - .env.db
    restart: always
    depends_on:
      - motivatr-payment-db


  motivatr-payment-db:
    container_name: motivatr-payment-db
    image: postgres:17
    env_file:
      - ./.env.db
    ports:
      - "10300:5432"
    volumes:
      - /var/lib/docker/volumes/motivatr/postgres/payment:/var/lib/postgresql/data
    restart: always


networks:
  default:
    external: true
    name: motivatr-shared-network